name: Rust

on:
  push:
    branches: [ master ]
    paths:
      - 'bin/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'bin/**'

defaults:
  run:
    working-directory: bin

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build release
      if: ${{ github.event == 'push' && success() }}
      run: cargo build --release --verbose
    - name: Release built binary
      uses: yakuhzi/action-release@v1.2.0
      if: ${{ github.event == 'push' && success() }}
      with:
        file: bin/target/release/bean-copy-txn
