name: Rust

on:
  push:
    tags:
      - v*

defaults:
  run:
    working-directory: bin

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build release
      run: cargo build --release --verbose
    - name: Release built binary
      uses: yakuhzi/action-release@v1.2.0
      with:
        file: bin/target/release/bean-copy-txn
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
